services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: super
      POSTGRES_PASSWORD: tim123
      POSTGRES_DB: task
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "super", "-d", "task" ]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  db_data: